/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsCard {
    }
    interface DsText {
    }
}
declare global {
    interface HTMLDsCardElement extends Components.DsCard, HTMLStencilElement {
    }
    var HTMLDsCardElement: {
        prototype: HTMLDsCardElement;
        new (): HTMLDsCardElement;
    };
    interface HTMLDsTextElement extends Components.DsText, HTMLStencilElement {
    }
    var HTMLDsTextElement: {
        prototype: HTMLDsTextElement;
        new (): HTMLDsTextElement;
    };
    interface HTMLElementTagNameMap {
        "ds-card": HTMLDsCardElement;
        "ds-text": HTMLDsTextElement;
    }
}
declare namespace LocalJSX {
    interface DsCard {
    }
    interface DsText {
    }
    interface IntrinsicElements {
        "ds-card": DsCard;
        "ds-text": DsText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-card": LocalJSX.DsCard & JSXBase.HTMLAttributes<HTMLDsCardElement>;
            "ds-text": LocalJSX.DsText & JSXBase.HTMLAttributes<HTMLDsTextElement>;
        }
    }
}
